codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    patch:
      default:
        target: '80'
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
  notify:
    gitter:
      default:
        url: "https://webhooks.gitter.im/e/42136d49f4c9c5fd2611"
        threshold: 1%

comment: off
